---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Warsaw
      - WEBUI_PORT=9092
    volumes:
      - /share/BigChungus/config/qBittorrent:/config
      - /share/BigChungus:/downloads
    ports:
      - 9092:9092
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

